name: 'AI Pull Request Reviewer'
description: 'Automatically review pull requests using AI to provide detailed feedback'
author: 'helixiora'

inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ github.token }}
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    REPO_NAME: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
